version: "3"
services:
  good_kensaku-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./data:/usr/src/app/data"
    depends_on:
      - redis
    networks:
      - default
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    expose:
      - "6379"
    networks:
      - default
 