# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, urls: List[str]=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param urls: The urls of this Body.  # noqa: E501
        :type urls: List[str]
        """
        self.swagger_types = {
            'urls': List[str]
        }

        self.attribute_map = {
            'urls': 'urls'
        }
        self._urls = urls

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def urls(self) -> List[str]:
        """Gets the urls of this Body.


        :return: The urls of this Body.
        :rtype: List[str]
        """
        return self._urls

    @urls.setter
    def urls(self, urls: List[str]):
        """Sets the urls of this Body.


        :param urls: The urls of this Body.
        :type urls: List[str]
        """

        self._urls = urls
