# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, user_evaluation: bool=None):  # noqa: E501
        """Body1 - a model defined in Swagger

        :param url: The url of this Body1.  # noqa: E501
        :type url: str
        :param user_evaluation: The user_evaluation of this Body1.  # noqa: E501
        :type user_evaluation: bool
        """
        self.swagger_types = {
            'url': str,
            'user_evaluation': bool
        }

        self.attribute_map = {
            'url': 'url',
            'user_evaluation': 'user_evaluation'
        }
        self._url = url
        self._user_evaluation = user_evaluation

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_1 of this Body1.  # noqa: E501
        :rtype: Body1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Body1.


        :return: The url of this Body1.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Body1.


        :param url: The url of this Body1.
        :type url: str
        """

        self._url = url

    @property
    def user_evaluation(self) -> bool:
        """Gets the user_evaluation of this Body1.


        :return: The user_evaluation of this Body1.
        :rtype: bool
        """
        return self._user_evaluation

    @user_evaluation.setter
    def user_evaluation(self, user_evaluation: bool):
        """Sets the user_evaluation of this Body1.


        :param user_evaluation: The user_evaluation of this Body1.
        :type user_evaluation: bool
        """

        self._user_evaluation = user_evaluation
